### PR TITLE
Redirect ServerFoundCallback to be invoked on the main thread + Continue server discovery even after one server is found

### PR DESCRIPTION
**Pull request by emredesu**
Currently, when a server is found, the `ServerFoundCallback` is invoked in the worker thread that was started with the `Task.Run()` command. Invoking the `ServerFoundCallback` on the worker thread causes its linked delegates (e.g. `ServerFoundCallback += OnServerFound`) to also be executed on the worker thread. If the delegate calls ANYTHING related to Unity engine (such as enabling/disabling GameObjects), this either causes an error or your calls to be completely ignored, as Unity hates any code that is not run on the main thread. This commit changes this, and invokes the callback inside the Update() function, which ensures that the callback occurs in the main thread.

I have encountered this issue while I was building my main menu UI for local connections. I wanted to enable a button that would help you connect to the server whenever one was found, however it didn't work. Upon applying the fix on this commit, I was able to get my buttons to enable without a problem. 

In addition, previously, the server discovery would instantly stop after a server was found, so if there were more than one server on your network, you were out of luck. This commit also fixes that, and allows the script to discover more than the first server by saving the previously found servers on a list, and then comparing the newly found endpoints to the previous ones to check if they are newly discovered servers.

### CODE REVIEW

**Comment by Abdelfattah-Radwan** [comment]
After further review of the code, the changes have been reverted due to the code being inefficient and the inconsistent code style.

**Comment by emredesu** [comment]
What part of it did you find inefficient?

**Comment by Abdelfattah-Radwan** [comment]
> What part of it did you find inefficient?

- Nested loops inside `Update` method
- Usage of `List<T>` instead of `HashSet<T>`
- Conversion of `IPAddress`s to `string`s for comparison instead of using the `IPAddress.Equals` method

**Comment by emredesu** [comment]
While I agree that the usage of `HashSet` would have been better, the other ones are not matters that were done by choice. `IPEndPoint.Equals` does not consistently return true in our case, as network conditions are _very_ prone to change and string comparison is the most reliable method, and the choice of using it `Update` was because we needed to return the invocation of the ServerFoundCallback back to the main thread (probably in an environment where `Time.timeScale` is set to 0 as LAN game searches will happen in the UI). If this was an update that was going to be overwritten by your own update anyways, why'd you revert what makes the code work for nanoseconds worth of optimizations?

**Comment by emredesu** [comment]
>This is a public project that people rely on in their projects, both during development and on release, having inefficient/poorly written code cannot be tolerated at all.

Yet it's been in this barely-functional state since your last commit which was over a year ago. I will admit that you are right in terms of the optimizations that could have been done much better (I am still a junior dev that is far from being able to write perfect code) but you could have actually compiled these mistakes for me to correct and I would have worked on that had you have good intentions. Keep your project and good luck in your future endeavors.

**Pull request merged**
